### ISSUE TITLE
Port Movim Android on Android 4

### ISSUE THREAD

**Issue by edhelas** [movim/movim_android#1]
The current app is only working on Android 5+

**Comment by keverets** [comment]
Today I found out that I can't update from 0.9 to 0.9.0.3 on F-droid, due to my phone being 4.4.4 and everything post 0.9 requires 5+.

Though latest & greatest leads to fancy features, backward compatibility (with progressive features) would aid adoption.

Just letting you know that you're losing at least this user (and likely more, along with their contacts that will no longer get exposure) due to this change.

**Comment by edhelas** [comment]
Thanks for your feedback. Actually the support of older versions of Android is a bit tricky because I'm currently using a specific WebView based on Chromium that seems to be available only on 5+.

**Comment by sim6** [comment]
I'm using FairPhone1U, AOSP 4.2.2, with f-droid. So I cannot update Movim and 0.9 have some bugs. :(

**Comment by edhelas** [comment]
I'm not planning to fix this issue, I didn't found any way to do it simply. Also I clearly have a lack of time (and I don't have a Android 4.\* device) to do it.
